
name: linkseq-demux

channels:
  - bioconda
  - Freenome
  - AgBiome
  - conda-forge

dependencies:
  - bcl2fastq=2.20
  - nextflow=20.01.0
  - fastqc=0.11.8
  - bbtools=37.62
  - fastp=0.20.0
  - sickle-trim=1.33
  - multiqc=1.8
